## Parsing Data from email receipts and storing it in a CSV file

In [160]:
import os
import pandas as pd

### lisitng out all the files in the driectory

In [161]:
folder_path=r'C:\Users\HP\Desktop\mic_research\email_receipts'
files=os.listdir(folder_path)

### Using mindee api to scrape data from receipts

In [162]:
from mindee import Client
  
my_client = Client().config_custom_doc(
    document_type="email_receipt",
    singular_name="custom_doc",
    plural_name="custom_docs",
    account_name="gsprabhu01",
    api_key="461b219887164a4a9dfd7a8367384306"
)

#### creating the dataframe

In [163]:
columns=['Order_id','Product_name','total_cost','address']
dt=pd.DataFrame(columns=columns)

## code to scrape data and append to dataframe

In [171]:
for i in range(7):
    
    #parsing through each receipt in the folder 
    my_doc = my_client.doc_from_path(folder_path+"\\"+files[i])
    parsed_doc = my_doc.parse("email_receipt")
    
    #storing feature data
    total_incl = parsed_doc.custom_doc.total_cost
    address= parsed_doc.custom_doc.address
    product_name= parsed_doc.custom_doc.product_name
    order_id= parsed_doc.custom_doc.order_id

    #creating list for multi word features such as address and product name
    l=[]
    for i in address['values']:
        l.append(i['content'])
    l=" ".join(l)    

    k=[]
    for i in product_name['values']:
        k.append(i['content'])
    k=" ".join(k)    

    #appending to the dataframe
    dt=dt.append({'Order_id':order_id['values'][0]['content'],'Product_name':k,'total_cost':total_incl['values'][0]['content'],'address':l},ignore_index=True)

## the dataframe

In [172]:
dt

,Order_id,Product_name,total_cost,address
0,00002476,Chicken Whopper Med,677.26,613 Block 14 mit Hostels eshwar nagar manipal
1,00010165,2 King Fries Easy Cheesy Dip,137.65,Name Gautam Prabhu 613 Block 14 mit Hostels es...
2,00002476,Chicken Whopper Med,677.26,613 Block 14 mit Hostels eshwar nagar manipal
3,00010165,2 King Fries Easy Cheesy Dip,137.65,Name Gautam Prabhu 613 Block 14 mit Hostels es...
4,00012169,1 Veg Whopper + Crispy Veg Burger Total,120.66,Name Mit manipal student plaza
5,1270939621,Chicken Biryani Chicken Roll Shawarma,398,411 B block 19 mit Hostels eshwar nagar manipa...
6,2832914747,American Brownie EL Veg Burger Concus Pizza Sp...,17.16,No.40 Retreat 18th main 12th B cross Ground Fl...
7,2954025513,Eggless Rich Truffle Cake,335,B1 502 Mohan Shiv
8,3726936209,Chocolate Truffle Cake Veg Burger [ 1 Veg Roll...,796.09,No.40 Retreat 18th main 12th B cross Ground Fl...
9,00002476,Chicken Whopper Med,677.26,613 Block 14 mit Hostels eshwar nagar manipal
10,00010165,2 King Fries Easy Cheesy Dip,137.65,Name Gautam Prabhu 613 Block 14 mit Hostels es...
11,00012169,1 Veg Whopper + Crispy Veg Burger Total,120.66,Name Mit manipal student plaza
12,1270939621,Chicken Biryani Chicken Roll Shawarma,398,411 B block 19 mit Hostels eshwar nagar manipa...
13,2832914747,American Brownie EL Veg Burger Concus Pizza Sp...,17.16,No.40 Retreat 18th main 12th B cross Ground Fl...
14,00002476,Chicken Whopper Med,677.26,613 Block 14 mit Hostels eshwar nagar manipal
15,00010165,2 King Fries Easy Cheesy Dip,137.65,Name Gautam Prabhu 613 Block 14 mit Hostels es...
16,00012169,1 Veg Whopper + Crispy Veg Burger Total,120.66,Name Mit manipal student plaza
17,1270939621,Chicken Biryani Chicken Roll Shawarma,398,411 B block 19 mit Hostels eshwar nagar manipa...
18,2832914747,American Brownie EL Veg Burger Concus Pizza Sp...,17.16,No.40 Retreat 18th main 12th B cross Ground Fl...
19,2954025513,Eggless Rich Truffle Cake,335,B1 502 Mohan Shiv
20,3726936209,Chocolate Truffle Cake Veg Burger [ 1 Veg Roll...,796.09,No.40 Retreat 18th main 12th B cross Ground Fl...

### storing it all in a csv file

In [174]:
dt.to_csv('data_from_email_receipts.csv')